# Generated by Django 4.2.4 on 2023-08-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_tag_options_rename_tags_article_scopes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='tags',
        ),
    ]
