# Generated by Django 4.2.4 on 2023-08-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_tags_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='scopes',
        ),
    ]
